DROP TABLE IF EXISTS car_models;

CREATE TABLE car_models (
  make_id VARCHAR(20) NOT NULL REFERENCES car_makes(id),
  id VARCHAR(20) NOT NULL ,
  title VARCHAR(60) NOT NULL ,

  PRIMARY KEY (id)
);

DELETE FROM car_models;

INSERT INTO car_models (make_id, id, title) VALUES
('ACURA', 'CL_MODELS', 'CL Models (4)'),
('ACURA', '2.2CL', ' - 2.2CL'),
('ACURA', '2.3CL', ' - 2.3CL'),
('ACURA', '3.0CL', ' - 3.0CL'),
('ACURA', '3.2CL', ' - 3.2CL'),
('ACURA', 'ILX', 'ILX'),
('ACURA', 'INTEG', 'Integra'),
('ACURA', 'LEGEND', 'Legend'),
('ACURA', 'MDX', 'MDX'),
('ACURA', 'NSX', 'NSX'),
('ACURA', 'RDX', 'RDX'),
('ACURA', 'RL_MODELS', 'RL Models (2)'),
('ACURA', '3.5RL', ' - 3.5 RL'),
('ACURA', 'RL', ' - RL'),
('ACURA', 'RSX', 'RSX'),
('ACURA', 'SLX', 'SLX'),
('ACURA', 'TL_MODELS', 'TL Models (3)'),
('ACURA', '2.5TL', ' - 2.5TL'),
('ACURA', '3.2TL', ' - 3.2TL'),
('ACURA', 'TL', ' - TL'),
('ACURA', 'TSX', 'TSX'),
('ACURA', 'VIGOR', 'Vigor'),
('ACURA', 'ZDX', 'ZDX'),
('ACURA', 'ACUOTH', 'Other Acura Models'),
('ALFA', 'ALFA164', '164'),
('ALFA', 'ALFA8C', '8C Competizione'),
('ALFA', 'ALFAGT', 'GTV-6'),
('ALFA', 'MIL', 'Milano'),
('ALFA', 'SPID', 'Spider'),
('ALFA', 'ALFAOTH', 'Other Alfa Romeo Models'),
('AMC', 'AMCALLIAN', 'Alliance'),
('AMC', 'CON', 'Concord'),
('AMC', 'EAGLE', 'Eagle'),
('AMC', 'AMCENC', 'Encore'),
('AMC', 'AMCSPIRIT', 'Spirit'),
('AMC', 'AMCOTH', 'Other AMC Models'),
('ASTON', 'DB7', 'DB7'),
('ASTON', 'DB9', 'DB9'),
('ASTON', 'DBS', 'DBS'),
('ASTON', 'LAGONDA', 'Lagonda'),
('ASTON', 'RAPIDE', 'Rapide'),
('ASTON', 'V12VANT', 'V12 Vantage'),
('ASTON', 'VANTAGE', 'V8 Vantage'),
('ASTON', 'VANQUISH', 'Vanquish'),
('ASTON', 'VIRAGE', 'Virage'),
('ASTON', 'UNAVAILAST', 'Other Aston Martin Models'),
('AUDI', 'AUDI100', '100'),
('AUDI', 'AUDI200', '200'),
('AUDI', '4000', '4000'),
('AUDI', '5000', '5000'),
('AUDI', '80', '80'),
('AUDI', '90', '90'),
('AUDI', 'A3', 'A3'),
('AUDI', 'A4', 'A4'),
('AUDI', 'A5', 'A5'),
('AUDI', 'A6', 'A6'),
('AUDI', 'A7', 'A7'),
('AUDI', 'A8', 'A8'),
('AUDI', 'ALLRDQUA', 'allroad'),
('AUDI', 'AUDICABRI', 'Cabriolet'),
('AUDI', 'AUDICOUPE', 'Coupe'),
('AUDI', 'Q3', 'Q3'),
('AUDI', 'Q5', 'Q5'),
('AUDI', 'Q7', 'Q7'),
('AUDI', 'QUATTR', 'Quattro'),
('AUDI', 'R8', 'R8'),
('AUDI', 'RS4', 'RS 4'),
('AUDI', 'RS5', 'RS 5'),
('AUDI', 'RS6', 'RS 6'),
('AUDI', 'S4', 'S4'),
('AUDI', 'S5', 'S5'),
('AUDI', 'S6', 'S6'),
('AUDI', 'S7', 'S7'),
('AUDI', 'S8', 'S8'),
('AUDI', 'TT', 'TT'),
('AUDI', 'TTRS', 'TT RS'),
('AUDI', 'TTS', 'TTS'),
('AUDI', 'V8', 'V8 Quattro'),
('AUDI', 'AUDOTH', 'Other Audi Models'),
('AVANTI', 'CONVERT', 'Convertible'),
('AVANTI', 'COUPEAVANT', 'Coupe'),
('AVANTI', 'SEDAN', 'Sedan'),
('AVANTI', 'UNAVAILAVA', 'Other Avanti Models'),
('BENTL', 'ARNAGE', 'Arnage'),
('BENTL', 'AZURE', 'Azure'),
('BENTL', 'BROOKLANDS', 'Brooklands'),
('BENTL', 'BENCONT', 'Continental'),
('BENTL', 'CORNICHE', 'Corniche'),
('BENTL', 'BENEIGHT', 'Eight'),
('BENTL', 'BENMUL', 'Mulsanne'),
('BENTL', 'BENTURBO', 'Turbo R'),
('BENTL', 'UNAVAILBEN', 'Other Bentley Models'),
('BMW', '1_SERIES', '1 Series (3)'),
('BMW', '128I', ' - 128i'),
('BMW', '135I', ' - 135i'),
('BMW', '135IS', ' - 135is'),
('BMW', '3_SERIES', '3 Series (29)'),
('BMW', '318I', ' - 318i'),
('BMW', '318IC', ' - 318iC'),
('BMW', '318IS', ' - 318iS'),
('BMW', '318TI', ' - 318ti'),
('BMW', '320I', ' - 320i'),
('BMW', '323CI', ' - 323ci'),
('BMW', '323I', ' - 323i'),
('BMW', '323IS', ' - 323is'),
('BMW', '323IT', ' - 323iT'),
('BMW', '325CI', ' - 325Ci'),
('BMW', '325E', ' - 325e'),
('BMW', '325ES', ' - 325es'),
('BMW', '325I', ' - 325i'),
('BMW', '325IS', ' - 325is'),
('BMW', '325IX', ' - 325iX'),
('BMW', '325XI', ' - 325xi'),
('BMW', '328CI', ' - 328Ci'),
('BMW', '328I', ' - 328i'),
('BMW', '328IS', ' - 328iS'),
('BMW', '328XI', ' - 328xi'),
('BMW', '330CI', ' - 330Ci'),
('BMW', '330I', ' - 330i'),
('BMW', '330XI', ' - 330xi'),
('BMW', '335D', ' - 335d'),
('BMW', '335I', ' - 335i'),
('BMW', '335IS', ' - 335is'),
('BMW', '335XI', ' - 335xi'),
('BMW', 'ACTIVE3', ' - ActiveHybrid 3'),
('BMW', 'BMW325', ' - 325'),
('BMW', '5_SERIES', '5 Series (19)'),
('BMW', '524TD', ' - 524td'),
('BMW', '525I', ' - 525i'),
('BMW', '525XI', ' - 525xi'),
('BMW', '528E', ' - 528e'),
('BMW', '528I', ' - 528i'),
('BMW', '528IT', ' - 528iT'),
('BMW', '528XI', ' - 528xi'),
('BMW', '530I', ' - 530i'),
('BMW', '530IT', ' - 530iT'),
('BMW', '530XI', ' - 530xi'),
('BMW', '533I', ' - 533i'),
('BMW', '535I', ' - 535i'),
('BMW', '535IGT', ' - 535i Gran Turismo'),
('BMW', '535XI', ' - 535xi'),
('BMW', '540I', ' - 540i'),
('BMW', '545I', ' - 545i'),
('BMW', '550I', ' - 550i'),
('BMW', '550IGT', ' - 550i Gran Turismo'),
('BMW', 'ACTIVE5', ' - ActiveHybrid 5'),
('BMW', '6_SERIES', '6 Series (8)'),
('BMW', '633CSI', ' - 633CSi'),
('BMW', '635CSI', ' - 635CSi'),
('BMW', '640I', ' - 640i'),
('BMW', '640IGC', ' - 640i Gran Coupe'),
('BMW', '645CI', ' - 645Ci'),
('BMW', '650I', ' - 650i'),
('BMW', '650IGC', ' - 650i Gran Coupe'),
('BMW', 'L6', ' - L6'),
('BMW', '7_SERIES', '7 Series (15)'),
('BMW', '733I', ' - 733i'),
('BMW', '735I', ' - 735i'),
('BMW', '735IL', ' - 735iL'),
('BMW', '740I', ' - 740i'),
('BMW', '740IL', ' - 740iL'),
('BMW', '740LI', ' - 740Li'),
('BMW', '745I', ' - 745i'),
('BMW', '745LI', ' - 745Li'),
('BMW', '750I', ' - 750i'),
('BMW', '750IL', ' - 750iL'),
('BMW', '750LI', ' - 750Li'),
('BMW', '760I', ' - 760i'),
('BMW', '760LI', ' - 760Li'),
('BMW', 'ACTIVE7', ' - ActiveHybrid 7'),
('BMW', 'ALPINAB7', ' - Alpina B7'),
('BMW', '8_SERIES', '8 Series (4)'),
('BMW', '840CI', ' - 840Ci'),
('BMW', '850CI', ' - 850Ci'),
('BMW', '850CSI', ' - 850CSi'),
('BMW', '850I', ' - 850i'),
('BMW', 'LΒ_SERIES', 'LΒ Series (1)'),
('BMW', 'L7', ' - L7'),
('BMW', 'M_SERIES', 'M Series (8)'),
('BMW', '1SERIESM', ' - 1 Series M'),
('BMW', 'BMWMCOUPE', ' - M Coupe'),
('BMW', 'BMWROAD', ' - M Roadster'),
('BMW', 'M3', ' - M3'),
('BMW', 'M5', ' - M5'),
('BMW', 'M6', ' - M6'),
('BMW', 'X5M', ' - X5 M'),
('BMW', 'X6M', ' - X6 M'),
('BMW', 'X_SERIES', 'X Series (5)'),
('BMW', 'ACTIVEX6', ' - ActiveHybrid X6'),
('BMW', 'X1', ' - X1'),
('BMW', 'X3', ' - X3'),
('BMW', 'X5', ' - X5'),
('BMW', 'X6', ' - X6'),
('BMW', 'Z_SERIES', 'Z Series (3)'),
('BMW', 'Z3', ' - Z3'),
('BMW', 'Z4', ' - Z4'),
('BMW', 'Z8', ' - Z8'),
('BMW', 'BMWOTH', 'Other BMW Models'),
('BUICK', 'CENT', 'Century'),
('BUICK', 'ELEC', 'Electra'),
('BUICK', 'ENCLAVE', 'Enclave'),
('BUICK', 'BUIENC', 'Encore'),
('BUICK', 'LACROSSE', 'LaCrosse'),
('BUICK', 'LESA', 'Le Sabre'),
('BUICK', 'LUCERNE', 'Lucerne'),
('BUICK', 'PARK', 'Park Avenue'),
('BUICK', 'RAINIER', 'Rainier'),
('BUICK', 'REATTA', 'Reatta'),
('BUICK', 'REG', 'Regal'),
('BUICK', 'RENDEZVOUS', 'Rendezvous'),
('BUICK', 'RIV', 'Riviera'),
('BUICK', 'BUICKROAD', 'Roadmaster'),
('BUICK', 'SKYH', 'Skyhawk'),
('BUICK', 'SKYL', 'Skylark'),
('BUICK', 'SOMER', 'Somerset'),
('BUICK', 'TERRAZA', 'Terraza'),
('BUICK', 'BUVERANO', 'Verano'),
('BUICK', 'BUOTH', 'Other Buick Models'),
('CAD', 'ALLANT', 'Allante'),
('CAD', 'ATS', 'ATS'),
('CAD', 'BROUGH', 'Brougham'),
('CAD', 'CATERA', 'Catera'),
('CAD', 'CIMA', 'Cimarron'),
('CAD', 'CTS', 'CTS'),
('CAD', 'DEV', 'De Ville'),
('CAD', 'DTS', 'DTS'),
('CAD', 'ELDO', 'Eldorado'),
('CAD', 'ESCALA', 'Escalade'),
('CAD', 'ESCALAESV', 'Escalade ESV'),
('CAD', 'EXT', 'Escalade EXT'),
('CAD', 'FLEE', 'Fleetwood'),
('CAD', 'SEV', 'Seville'),
('CAD', 'SRX', 'SRX'),
('CAD', 'STS', 'STS'),
('CAD', 'XLR', 'XLR'),
('CAD', 'XTS', 'XTS'),
('CAD', 'CADOTH', 'Other Cadillac Models'),
('CHEV', 'ASTRO', 'Astro'),
('CHEV', 'AVALNCH', 'Avalanche'),
('CHEV', 'AVEO', 'Aveo'),
('CHEV', 'AVEO5', 'Aveo5'),
('CHEV', 'BERETT', 'Beretta'),
('CHEV', 'BLAZER', 'Blazer'),
('CHEV', 'CAM', 'Camaro'),
('CHEV', 'CAP', 'Caprice'),
('CHEV', 'CHECAPS', 'Captiva Sport'),
('CHEV', 'CAV', 'Cavalier'),
('CHEV', 'CELE', 'Celebrity'),
('CHEV', 'CHEVETTE', 'Chevette'),
('CHEV', 'CITATION', 'Citation'),
('CHEV', 'COBALT', 'Cobalt'),
('CHEV', 'COLORADO', 'Colorado'),
('CHEV', 'CORSI', 'Corsica'),
('CHEV', 'CORV', 'Corvette'),
('CHEV', 'CRUZE', 'Cruze'),
('CHEV', 'ELCAM', 'El Camino'),
('CHEV', 'EQUINOX', 'Equinox'),
('CHEV', 'G15EXP', 'Express Van'),
('CHEV', 'G10', 'G Van'),
('CHEV', 'HHR', 'HHR'),
('CHEV', 'CHEVIMP', 'Impala'),
('CHEV', 'KODC4500', 'Kodiak C4500'),
('CHEV', 'LUMINA', 'Lumina'),
('CHEV', 'LAPV', 'Lumina APV'),
('CHEV', 'LUV', 'LUV'),
('CHEV', 'MALI', 'Malibu'),
('CHEV', 'CHVMETR', 'Metro'),
('CHEV', 'CHEVMONT', 'Monte Carlo'),
('CHEV', 'NOVA', 'Nova'),
('CHEV', 'CHEVPRIZM', 'Prizm'),
('CHEV', 'CHVST', 'S10 Blazer'),
('CHEV', 'S10PICKUP', 'S10 Pickup'),
('CHEV', 'CHEV150', 'Silverado and other C/K1500'),
('CHEV', 'CHEVC25', 'Silverado and other C/K2500'),
('CHEV', 'CH3500PU', 'Silverado and other C/K3500'),
('CHEV', 'SONIC', 'Sonic'),
('CHEV', 'SPARK', 'Spark'),
('CHEV', 'CHEVSPEC', 'Spectrum'),
('CHEV', 'CHSPRINT', 'Sprint'),
('CHEV', 'SSR', 'SSR'),
('CHEV', 'CHEVSUB', 'Suburban'),
('CHEV', 'TAHOE', 'Tahoe'),
('CHEV', 'TRACKE', 'Tracker'),
('CHEV', 'TRAILBLZ', 'TrailBlazer'),
('CHEV', 'TRAILBZEXT', 'TrailBlazer EXT'),
('CHEV', 'TRAVERSE', 'Traverse'),
('CHEV', 'UPLANDER', 'Uplander'),
('CHEV', 'VENTUR', 'Venture'),
('CHEV', 'VOLT', 'Volt'),
('CHEV', 'CHEOTH', 'Other Chevrolet Models'),
('CHRY', 'CHRYS200', '200'),
('CHRY', '300', '300'),
('CHRY', 'CHRY300', '300M'),
('CHRY', 'ASPEN', 'Aspen'),
('CHRY', 'CARAVAN', 'Caravan'),
('CHRY', 'CIRRUS', 'Cirrus'),
('CHRY', 'CONC', 'Concorde'),
('CHRY', 'CHRYCONQ', 'Conquest'),
('CHRY', 'CORDOBA', 'Cordoba'),
('CHRY', 'CROSSFIRE', 'Crossfire'),
('CHRY', 'ECLASS', 'E Class'),
('CHRY', 'FIFTH', 'Fifth Avenue'),
('CHRY', 'CHRYGRANDV', 'Grand Voyager'),
('CHRY', 'IMPE', 'Imperial'),
('CHRY', 'INTREPID', 'Intrepid'),
('CHRY', 'CHRYLAS', 'Laser'),
('CHRY', 'LEBA', 'LeBaron'),
('CHRY', 'LHS', 'LHS'),
('CHRY', 'CHRYNEON', 'Neon'),
('CHRY', 'NY', 'New Yorker'),
('CHRY', 'NEWPORT', 'Newport'),
('CHRY', 'PACIFICA', 'Pacifica'),
('CHRY', 'CHPROWLE', 'Prowler'),
('CHRY', 'PTCRUIS', 'PT Cruiser'),
('CHRY', 'CHRYSEB', 'Sebring'),
('CHRY', 'CHRYTC', 'TC by Maserati'),
('CHRY', 'TANDC', 'Town & Country'),
('CHRY', 'VOYAGER', 'Voyager'),
('CHRY', 'CHOTH', 'Other Chrysler Models'),
('DAEW', 'LANOS', 'Lanos'),
('DAEW', 'LEGANZA', 'Leganza'),
('DAEW', 'NUBIRA', 'Nubira'),
('DAEW', 'DAEOTH', 'Other Daewoo Models'),
('DAIHAT', 'CHAR', 'Charade'),
('DAIHAT', 'ROCKY', 'Rocky'),
('DAIHAT', 'DAIHOTH', 'Other Daihatsu Models'),
('DATSUN', 'DAT200SX', '200SX'),
('DATSUN', 'DAT210', '210'),
('DATSUN', '280Z', '280ZX'),
('DATSUN', '300ZX', '300ZX'),
('DATSUN', '310', '310'),
('DATSUN', '510', '510'),
('DATSUN', '720', '720'),
('DATSUN', '810', '810'),
('DATSUN', 'DATMAX', 'Maxima'),
('DATSUN', 'DATPU', 'Pickup'),
('DATSUN', 'PUL', 'Pulsar'),
('DATSUN', 'DATSENT', 'Sentra'),
('DATSUN', 'STAN', 'Stanza'),
('DATSUN', 'DATOTH', 'Other Datsun Models'),
('DELOREAN', 'DMC12', 'DMC-12'),
('DODGE', '400', '400'),
('DODGE', 'DOD600', '600'),
('DODGE', 'ARI', 'Aries'),
('DODGE', 'AVENGR', 'Avenger'),
('DODGE', 'CALIBER', 'Caliber'),
('DODGE', 'DODCARA', 'Caravan'),
('DODGE', 'CHALLENGER', 'Challenger'),
('DODGE', 'DODCHAR', 'Charger'),
('DODGE', 'DODCOLT', 'Colt'),
('DODGE', 'DODCONQ', 'Conquest'),
('DODGE', 'DODDW', 'D/W Truck'),
('DODGE', 'DAKOTA', 'Dakota'),
('DODGE', 'DODDART', 'Dart'),
('DODGE', 'DAY', 'Daytona'),
('DODGE', 'DIPLOMA', 'Diplomat'),
('DODGE', 'DURANG', 'Durango'),
('DODGE', 'DODDYNA', 'Dynasty'),
('DODGE', 'GRANDCARAV', 'Grand Caravan'),
('DODGE', 'INTRE', 'Intrepid'),
('DODGE', 'JOURNEY', 'Journey'),
('DODGE', 'LANCERDODG', 'Lancer'),
('DODGE', 'MAGNUM', 'Magnum'),
('DODGE', 'MIRADA', 'Mirada'),
('DODGE', 'MONACO', 'Monaco'),
('DODGE', 'DODNEON', 'Neon'),
('DODGE', 'NITRO', 'Nitro'),
('DODGE', 'OMNI', 'Omni'),
('DODGE', 'RAIDER', 'Raider'),
('DODGE', 'RAM1504WD', 'Ram 1500 Truck'),
('DODGE', 'RAM25002WD', 'Ram 2500 Truck'),
('DODGE', 'RAM3502WD', 'Ram 3500 Truck'),
('DODGE', 'RAM4500', 'Ram 4500 Truck'),
('DODGE', 'DODD50', 'Ram 50 Truck'),
('DODGE', 'CV', 'RAM C/V'),
('DODGE', 'RAMSRT10', 'Ram SRT-10'),
('DODGE', 'RAMVANV8', 'Ram Van'),
('DODGE', 'RAMWAGON', 'Ram Wagon'),
('DODGE', 'RAMCGR', 'Ramcharger'),
('DODGE', 'RAMPAGE', 'Rampage'),
('DODGE', 'DODSHAD', 'Shadow'),
('DODGE', 'DODSPIR', 'Spirit'),
('DODGE', 'SPRINTER', 'Sprinter'),
('DODGE', 'SRT4', 'SRT-4'),
('DODGE', 'STREGIS', 'St. Regis'),
('DODGE', 'STEAL', 'Stealth'),
('DODGE', 'STRATU', 'Stratus'),
('DODGE', 'VIPER', 'Viper'),
('DODGE', 'DOOTH', 'Other Dodge Models'),
('EAGLE', 'EAGLEMED', 'Medallion'),
('EAGLE', 'EAGLEPREM', 'Premier'),
('EAGLE', 'SUMMIT', 'Summit'),
('EAGLE', 'TALON', 'Talon'),
('EAGLE', 'VISION', 'Vision'),
('EAGLE', 'EAGOTH', 'Other Eagle Models'),
('FER', '308GTB', '308 GTB Quattrovalvole'),
('FER', '308TBI', '308 GTBI'),
('FER', '308GTS', '308 GTS Quattrovalvole'),
('FER', '308TSI', '308 GTSI'),
('FER', '328GTB', '328 GTB'),
('FER', '328GTS', '328 GTS'),
('FER', '348GTB', '348 GTB'),
('FER', '348GTS', '348 GTS'),
('FER', '348SPI', '348 Spider'),
('FER', '348TB', '348 TB'),
('FER', '348TS', '348 TS'),
('FER', '360', '360'),
('FER', '456GT', '456 GT'),
('FER', '456MGT', '456M GT'),
('FER', '458ITALIA', '458 Italia'),
('FER', '512BBI', '512 BBi'),
('FER', '512M', '512M'),
('FER', '512TR', '512TR'),
('FER', '550M', '550 Maranello'),
('FER', '575M', '575M Maranello'),
('FER', '599GTB', '599 GTB Fiorano'),
('FER', '599GTO', '599 GTO'),
('FER', '612SCAGLIE', '612 Scaglietti'),
('FER', 'FERCALIF', 'California'),
('FER', 'ENZO', 'Enzo'),
('FER', 'F355', 'F355'),
('FER', 'F40', 'F40'),
('FER', 'F430', 'F430'),
('FER', 'F50', 'F50'),
('FER', 'FERFF', 'FF'),
('FER', 'MOND', 'Mondial'),
('FER', 'TEST', 'Testarossa'),
('FER', 'UNAVAILFER', 'Other Ferrari Models'),
('FIAT', '2000', '2000 Spider'),
('FIAT', 'FIAT500', '500'),
('FIAT', 'BERTON', 'Bertone X1/9'),
('FIAT', 'BRAVA', 'Brava'),
('FIAT', 'PININ', 'Pininfarina Spider'),
('FIAT', 'STRADA', 'Strada'),
('FIAT', 'FIATX19', 'X1/9'),
('FIAT', 'UNAVAILFIA', 'Other Fiat Models'),
('FISK', 'KARMA', 'Karma'),
('FORD', 'AERO', 'Aerostar'),
('FORD', 'ASPIRE', 'Aspire'),
('FORD', 'BRON', 'Bronco'),
('FORD', 'B2', 'Bronco II'),
('FORD', 'FOCMAX', 'C-MAX'),
('FORD', 'FORDCLUB', 'Club Wagon'),
('FORD', 'CONTOUR', 'Contour'),
('FORD', 'COURIER', 'Courier'),
('FORD', 'CROWNVIC', 'Crown Victoria'),
('FORD', 'E150ECON', 'E-150 and Econoline 150'),
('FORD', 'E250ECON', 'E-250 and Econoline 250'),
('FORD', 'E350ECON', 'E-350 and Econoline 350'),
('FORD', 'EDGE', 'Edge'),
('FORD', 'ESCAPE', 'Escape'),
('FORD', 'ESCO', 'Escort'),
('FORD', 'EXCURSION', 'Excursion'),
('FORD', 'EXP', 'EXP'),
('FORD', 'EXPEDI', 'Expedition'),
('FORD', 'EXPEDIEL', 'Expedition EL'),
('FORD', 'EXPLOR', 'Explorer'),
('FORD', 'SPORTTRAC', 'Explorer Sport Trac'),
('FORD', 'F100', 'F100'),
('FORD', 'F150PICKUP', 'F150'),
('FORD', 'F250', 'F250'),
('FORD', 'F350', 'F350'),
('FORD', 'F450', 'F450'),
('FORD', 'FAIRM', 'Fairmont'),
('FORD', 'FESTIV', 'Festiva'),
('FORD', 'FIESTA', 'Fiesta'),
('FORD', 'FIVEHUNDRE', 'Five Hundred'),
('FORD', 'FLEX', 'Flex'),
('FORD', 'FOCUS', 'Focus'),
('FORD', 'FREESTAR', 'Freestar'),
('FORD', 'FREESTYLE', 'Freestyle'),
('FORD', 'FUSION', 'Fusion'),
('FORD', 'GRANADA', 'Granada'),
('FORD', 'GT', 'GT'),
('FORD', 'LTD', 'LTD'),
('FORD', 'MUST', 'Mustang'),
('FORD', 'PROBE', 'Probe'),
('FORD', 'RANGER', 'Ranger'),
('FORD', 'TAURUS', 'Taurus'),
('FORD', 'TAURUSX', 'Taurus X'),
('FORD', 'TEMPO', 'Tempo'),
('FORD', 'TBIRD', 'Thunderbird'),
('FORD', 'TRANSCONN', 'Transit Connect'),
('FORD', 'WINDST', 'Windstar'),
('FORD', 'FORDZX2', 'ZX2 Escort'),
('FORD', 'FOOTH', 'Other Ford Models'),
('FREIGHT', 'FRESPRINT', 'Sprinter'),
('GEO', 'GEOMETRO', 'Metro'),
('GEO', 'GEOPRIZM', 'Prizm'),
('GEO', 'SPECT', 'Spectrum'),
('GEO', 'STORM', 'Storm'),
('GEO', 'GEOTRACK', 'Tracker'),
('GEO', 'GEOOTH', 'Other Geo Models'),
('GMC', 'ACADIA', 'Acadia'),
('GMC', 'CABALLERO', 'Caballero'),
('GMC', 'CANYON', 'Canyon'),
('GMC', 'ENVOY', 'Envoy'),
('GMC', 'ENVOYXL', 'Envoy XL'),
('GMC', 'ENVOYXUV', 'Envoy XUV'),
('GMC', 'JIM', 'Jimmy'),
('GMC', 'RALLYWAG', 'Rally Wagon'),
('GMC', 'GMCS15', 'S15 Jimmy'),
('GMC', 'S15', 'S15 Pickup'),
('GMC', 'SAFARIGMC', 'Safari'),
('GMC', 'GMCSAVANA', 'Savana'),
('GMC', '15SIPU4WD', 'Sierra C/K1500'),
('GMC', 'GMCC25PU', 'Sierra C/K2500'),
('GMC', 'GMC3500PU', 'Sierra C/K3500'),
('GMC', 'SONOMA', 'Sonoma'),
('GMC', 'SUB', 'Suburban'),
('GMC', 'GMCSYCLON', 'Syclone'),
('GMC', 'TERRAIN', 'Terrain'),
('GMC', 'TOPC4500', 'TopKick C4500'),
('GMC', 'TYPH', 'Typhoon'),
('GMC', 'GMCVANDUR', 'Vandura'),
('GMC', 'YUKON', 'Yukon'),
('GMC', 'YUKONXL', 'Yukon XL'),
('GMC', 'GMCOTH', 'Other GMC Models'),
('HONDA', 'ACCORD', 'Accord'),
('HONDA', 'CIVIC', 'Civic'),
('HONDA', 'CRV', 'CR-V'),
('HONDA', 'CRZ', 'CR-Z'),
('HONDA', 'CRX', 'CRX'),
('HONDA', 'CROSSTOUR_MODELS', 'Crosstour and Accord Crosstour Models (2)'),
('HONDA', 'CROSSTOUR', ' - Accord Crosstour'),
('HONDA', 'HONCROSS', ' - Crosstour'),
('HONDA', 'HONDELSOL', 'Del Sol'),
('HONDA', 'ELEMENT', 'Element'),
('HONDA', 'FIT', 'Fit'),
('HONDA', 'INSIGHT', 'Insight'),
('HONDA', 'ODYSSEY', 'Odyssey'),
('HONDA', 'PASSPO', 'Passport'),
('HONDA', 'PILOT', 'Pilot'),
('HONDA', 'PRE', 'Prelude'),
('HONDA', 'RIDGELINE', 'Ridgeline'),
('HONDA', 'S2000', 'S2000'),
('HONDA', 'HONOTH', 'Other Honda Models'),
('AMGEN', 'HUMMER', 'H1'),
('AMGEN', 'H2', 'H2'),
('AMGEN', 'H3', 'H3'),
('AMGEN', 'H3T', 'H3T'),
('AMGEN', 'AMGOTH', 'Other Hummer Models'),
('HYUND', 'ACCENT', 'Accent'),
('HYUND', 'AZERA', 'Azera'),
('HYUND', 'ELANTR', 'Elantra'),
('HYUND', 'HYUELANCPE', 'Elantra Coupe'),
('HYUND', 'ELANTOUR', 'Elantra Touring'),
('HYUND', 'ENTOURAGE', 'Entourage'),
('HYUND', 'EQUUS', 'Equus'),
('HYUND', 'HYUEXCEL', 'Excel'),
('HYUND', 'GENESIS', 'Genesis'),
('HYUND', 'GENESISCPE', 'Genesis Coupe'),
('HYUND', 'SANTAFE', 'Santa Fe'),
('HYUND', 'SCOUPE', 'Scoupe'),
('HYUND', 'SONATA', 'Sonata'),
('HYUND', 'TIBURO', 'Tiburon'),
('HYUND', 'TUCSON', 'Tucson'),
('HYUND', 'VELOSTER', 'Veloster'),
('HYUND', 'VERACRUZ', 'Veracruz'),
('HYUND', 'XG300', 'XG300'),
('HYUND', 'XG350', 'XG350'),
('HYUND', 'HYUOTH', 'Other Hyundai Models'),
('INFIN', 'EX_MODELS', 'EX Models (2)'),
('INFIN', 'EX35', ' - EX35'),
('INFIN', 'EX37', ' - EX37'),
('INFIN', 'FX_MODELS', 'FX Models (4)'),
('INFIN', 'FX35', ' - FX35'),
('INFIN', 'FX37', ' - FX37'),
('INFIN', 'FX45', ' - FX45'),
('INFIN', 'FX50', ' - FX50'),
('INFIN', 'G_MODELS', 'G Models (4)'),
('INFIN', 'G20', ' - G20'),
('INFIN', 'G25', ' - G25'),
('INFIN', 'G35', ' - G35'),
('INFIN', 'G37', ' - G37'),
('INFIN', 'I_MODELS', 'I Models (2)'),
('INFIN', 'I30', ' - I30'),
('INFIN', 'I35', ' - I35'),
('INFIN', 'J_MODELS', 'J Models (1)'),
('INFIN', 'J30', ' - J30'),
('INFIN', 'JX_MODELS', 'JX Models (1)'),
('INFIN', 'JX35', ' - JX35'),
('INFIN', 'M_MODELS', 'M Models (6)'),
('INFIN', 'M30', ' - M30'),
('INFIN', 'M35', ' - M35'),
('INFIN', 'M35HYBRID', ' - M35h'),
('INFIN', 'M37', ' - M37'),
('INFIN', 'M45', ' - M45'),
('INFIN', 'M56', ' - M56'),
('INFIN', 'Q_MODELS', 'Q Models (1)'),
('INFIN', 'Q45', ' - Q45'),
('INFIN', 'QX_MODELS', 'QX Models (2)'),
('INFIN', 'QX4', ' - QX4'),
('INFIN', 'QX56', ' - QX56'),
('INFIN', 'INFOTH', 'Other Infiniti Models'),
('ISU', 'AMIGO', 'Amigo'),
('ISU', 'ASCENDER', 'Ascender'),
('ISU', 'AXIOM', 'Axiom'),
('ISU', 'HOMBRE', 'Hombre'),
('ISU', 'I280', 'i-280'),
('ISU', 'I290', 'i-290'),
('ISU', 'I350', 'i-350'),
('ISU', 'I370', 'i-370'),
('ISU', 'ISUMARK', 'I-Mark'),
('ISU', 'ISUIMP', 'Impulse'),
('ISU', 'OASIS', 'Oasis'),
('ISU', 'ISUPU', 'Pickup'),
('ISU', 'RODEO', 'Rodeo'),
('ISU', 'STYLUS', 'Stylus'),
('ISU', 'TROOP', 'Trooper'),
('ISU', 'TRP2', 'Trooper II'),
('ISU', 'VEHICROSS', 'VehiCROSS'),
('ISU', 'ISUOTH', 'Other Isuzu Models'),
('JAG', 'STYPE', 'S-Type'),
('JAG', 'XTYPE', 'X-Type'),
('JAG', 'XF', 'XF'),
('JAG', 'XJ_SERIES', 'XJ Series (10)'),
('JAG', 'JAGXJ12', ' - XJ12'),
('JAG', 'JAGXJ6', ' - XJ6'),
('JAG', 'JAGXJR', ' - XJR'),
('JAG', 'JAGXJRS', ' - XJR-S'),
('JAG', 'JAGXJS', ' - XJS'),
('JAG', 'VANDEN', ' - XJ Vanden Plas'),
('JAG', 'XJ', ' - XJ'),
('JAG', 'XJ8', ' - XJ8'),
('JAG', 'XJ8L', ' - XJ8 L'),
('JAG', 'XJSPORT', ' - XJ Sport'),
('JAG', 'XK_SERIES', 'XK Series (3)'),
('JAG', 'JAGXK8', ' - XK8'),
('JAG', 'XK', ' - XK'),
('JAG', 'XKR', ' - XKR'),
('JAG', 'JAGOTH', 'Other Jaguar Models'),
('JEEP', 'CHER', 'Cherokee'),
('JEEP', 'JEEPCJ', 'CJ'),
('JEEP', 'COMANC', 'Comanche'),
('JEEP', 'COMMANDER', 'Commander'),
('JEEP', 'COMPASS', 'Compass'),
('JEEP', 'JEEPGRAND', 'Grand Cherokee'),
('JEEP', 'GRWAG', 'Grand Wagoneer'),
('JEEP', 'LIBERTY', 'Liberty'),
('JEEP', 'PATRIOT', 'Patriot'),
('JEEP', 'JEEPPU', 'Pickup'),
('JEEP', 'SCRAMBLE', 'Scrambler'),
('JEEP', 'WAGONE', 'Wagoneer'),
('JEEP', 'WRANGLER', 'Wrangler'),
('JEEP', 'JEOTH', 'Other Jeep Models'),
('KIA', 'AMANTI', 'Amanti'),
('KIA', 'BORREGO', 'Borrego'),
('KIA', 'FORTE', 'Forte'),
('KIA', 'FORTEKOUP', 'Forte Koup'),
('KIA', 'OPTIMA', 'Optima'),
('KIA', 'RIO', 'Rio'),
('KIA', 'RIO5', 'Rio5'),
('KIA', 'RONDO', 'Rondo'),
('KIA', 'SEDONA', 'Sedona'),
('KIA', 'SEPHIA', 'Sephia'),
('KIA', 'SORENTO', 'Sorento'),
('KIA', 'SOUL', 'Soul'),
('KIA', 'SPECTRA', 'Spectra'),
('KIA', 'SPECTRA5', 'Spectra5'),
('KIA', 'SPORTA', 'Sportage'),
('KIA', 'KIAOTH', 'Other Kia Models'),
('LAM', 'AVENT', 'Aventador'),
('LAM', 'COUNT', 'Countach'),
('LAM', 'DIABLO', 'Diablo'),
('LAM', 'GALLARDO', 'Gallardo'),
('LAM', 'JALPA', 'Jalpa'),
('LAM', 'LM002', 'LM002'),
('LAM', 'MURCIELAGO', 'Murcielago'),
('LAM', 'UNAVAILLAM', 'Other Lamborghini Models'),
('LAN', 'BETA', 'Beta'),
('LAN', 'ZAGATO', 'Zagato'),
('LAN', 'UNAVAILLAN', 'Other Lancia Models'),
('ROV', 'DEFEND', 'Defender'),
('ROV', 'DISCOV', 'Discovery'),
('ROV', 'FRELNDR', 'Freelander'),
('ROV', 'LR2', 'LR2'),
('ROV', 'LR3', 'LR3'),
('ROV', 'LR4', 'LR4'),
('ROV', 'RANGE', 'Range Rover'),
('ROV', 'EVOQUE', 'Range Rover Evoque'),
('ROV', 'RANGESPORT', 'Range Rover Sport'),
('ROV', 'ROVOTH', 'Other Land Rover Models'),
('LEXUS', 'CT_MODELS', 'CT Models (1)'),
('LEXUS', 'CT200H', ' - CT 200h'),
('LEXUS', 'ES_MODELS', 'ES Models (5)'),
('LEXUS', 'ES250', ' - ES 250'),
('LEXUS', 'ES300', ' - ES 300'),
('LEXUS', 'ES300H', ' - ES 300h'),
('LEXUS', 'ES330', ' - ES 330'),
('LEXUS', 'ES350', ' - ES 350'),
('LEXUS', 'GS_MODELS', 'GS Models (6)'),
('LEXUS', 'GS300', ' - GS 300'),
('LEXUS', 'GS350', ' - GS 350'),
('LEXUS', 'GS400', ' - GS 400'),
('LEXUS', 'GS430', ' - GS 430'),
('LEXUS', 'GS450H', ' - GS 450h'),
('LEXUS', 'GS460', ' - GS 460'),
('LEXUS', 'GX_MODELS', 'GX Models (2)'),
('LEXUS', 'GX460', ' - GX 460'),
('LEXUS', 'GX470', ' - GX 470'),
('LEXUS', 'HS_MODELS', 'HS Models (1)'),
('LEXUS', 'HS250H', ' - HS 250h'),
('LEXUS', 'IS_MODELS', 'IS Models (6)'),
('LEXUS', 'IS250', ' - IS 250'),
('LEXUS', 'IS250C', ' - IS 250C'),
('LEXUS', 'IS300', ' - IS 300'),
('LEXUS', 'IS350', ' - IS 350'),
('LEXUS', 'IS350C', ' - IS 350C'),
('LEXUS', 'ISF', ' - IS F'),
('LEXUS', 'LEXLFA', 'LFA'),
('LEXUS', 'LS_MODELS', 'LS Models (4)'),
('LEXUS', 'LS400', ' - LS 400'),
('LEXUS', 'LS430', ' - LS 430'),
('LEXUS', 'LS460', ' - LS 460'),
('LEXUS', 'LS600H', ' - LS 600h'),
('LEXUS', 'LX_MODELS', 'LX Models (3)'),
('LEXUS', 'LX450', ' - LX 450'),
('LEXUS', 'LX470', ' - LX 470'),
('LEXUS', 'LX570', ' - LX 570'),
('LEXUS', 'RX_MODELS', 'RX Models (5)'),
('LEXUS', 'RX300', ' - RX 300'),
('LEXUS', 'RX330', ' - RX 330'),
('LEXUS', 'RX350', ' - RX 350'),
('LEXUS', 'RX400H', ' - RX 400h'),
('LEXUS', 'RX450H', ' - RX 450h'),
('LEXUS', 'SC_MODELS', 'SC Models (3)'),
('LEXUS', 'SC300', ' - SC 300'),
('LEXUS', 'SC400', ' - SC 400'),
('LEXUS', 'SC430', ' - SC 430'),
('LEXUS', 'LEXOTH', 'Other Lexus Models'),
('LINC', 'AVIATOR', 'Aviator'),
('LINC', 'BLKWOOD', 'Blackwood'),
('LINC', 'CONT', 'Continental'),
('LINC', 'LSLINCOLN', 'LS'),
('LINC', 'MARKLT', 'Mark LT'),
('LINC', 'MARK6', 'Mark VI'),
('LINC', 'MARK7', 'Mark VII'),
('LINC', 'MARK8', 'Mark VIII'),
('LINC', 'MKS', 'MKS'),
('LINC', 'MKT', 'MKT'),
('LINC', 'MKX', 'MKX'),
('LINC', 'MKZ', 'MKZ'),
('LINC', 'NAVIGA', 'Navigator'),
('LINC', 'NAVIGAL', 'Navigator L'),
('LINC', 'LINCTC', 'Town Car'),
('LINC', 'ZEPHYR', 'Zephyr'),
('LINC', 'LINOTH', 'Other Lincoln Models'),
('LOTUS', 'ELAN', 'Elan'),
('LOTUS', 'LOTELISE', 'Elise'),
('LOTUS', 'ESPRIT', 'Esprit'),
('LOTUS', 'EVORA', 'Evora'),
('LOTUS', 'EXIGE', 'Exige'),
('LOTUS', 'UNAVAILLOT', 'Other Lotus Models'),
('MAS', '430', '430'),
('MAS', 'BITRBO', 'Biturbo'),
('MAS', 'COUPEMAS', 'Coupe'),
('MAS', 'GRANSPORT', 'GranSport'),
('MAS', 'GRANTURISM', 'GranTurismo'),
('MAS', 'QP', 'Quattroporte'),
('MAS', 'SPYDER', 'Spyder'),
('MAS', 'UNAVAILMAS', 'Other Maserati Models'),
('MAYBACH', '57MAYBACH', '57'),
('MAYBACH', '62MAYBACH', '62'),
('MAYBACH', 'UNAVAILMAY', 'Other Maybach Models'),
('MAZDA', 'MAZDA323', '323'),
('MAZDA', 'MAZDA626', '626'),
('MAZDA', '929', '929'),
('MAZDA', 'B-SERIES', 'B-Series Pickup'),
('MAZDA', 'CX-5', 'CX-5'),
('MAZDA', 'CX-7', 'CX-7'),
('MAZDA', 'CX-9', 'CX-9'),
('MAZDA', 'GLC', 'GLC'),
('MAZDA', 'MAZDA2', 'MAZDA2'),
('MAZDA', 'MAZDA3', 'MAZDA3'),
('MAZDA', 'MAZDA5', 'MAZDA5'),
('MAZDA', 'MAZDA6', 'MAZDA6'),
('MAZDA', 'MAZDASPD3', 'MAZDASPEED3'),
('MAZDA', 'MAZDASPD6', 'MAZDASPEED6'),
('MAZDA', 'MIATA', 'Miata MX5'),
('MAZDA', 'MILL', 'Millenia'),
('MAZDA', 'MPV', 'MPV'),
('MAZDA', 'MX3', 'MX3'),
('MAZDA', 'MX6', 'MX6'),
('MAZDA', 'NAVAJO', 'Navajo'),
('MAZDA', 'PROTE', 'Protege'),
('MAZDA', 'PROTE5', 'Protege5'),
('MAZDA', 'RX7', 'RX-7'),
('MAZDA', 'RX8', 'RX-8'),
('MAZDA', 'TRIBUTE', 'Tribute'),
('MAZDA', 'MAZOTH', 'Other Mazda Models'),
('MCLAREN', 'MP4', 'MP4-12C'),
('MB', '190_CLASS', '190 Class (2)'),
('MB', '190D', ' - 190D'),
('MB', '190E', ' - 190E'),
('MB', '240_CLASS', '240 Class (1)'),
('MB', '240D', ' - 240D'),
('MB', '300_CLASS_E_CLASS', '300 Class / E Class (6)'),
('MB', '300CD', ' - 300CD'),
('MB', '300CE', ' - 300CE'),
('MB', '300D', ' - 300D'),
('MB', '300E', ' - 300E'),
('MB', '300TD', ' - 300TD'),
('MB', '300TE', ' - 300TE'),
('MB', 'C_CLASS', 'C Class (13)'),
('MB', 'C220', ' - C220'),
('MB', 'C230', ' - C230'),
('MB', 'C240', ' - C240'),
('MB', 'C250', ' - C250'),
('MB', 'C280', ' - C280'),
('MB', 'C300', ' - C300'),
('MB', 'C320', ' - C320'),
('MB', 'C32AMG', ' - C32 AMG'),
('MB', 'C350', ' - C350'),
('MB', 'C36AMG', ' - C36 AMG'),
('MB', 'C43AMG', ' - C43 AMG'),
('MB', 'C55AMG', ' - C55 AMG'),
('MB', 'C63AMG', ' - C63 AMG'),
('MB', 'CL_CLASS', 'CL Class (6)'),
('MB', 'CL500', ' - CL500'),
('MB', 'CL550', ' - CL550'),
('MB', 'CL55AMG', ' - CL55 AMG'),
('MB', 'CL600', ' - CL600'),
('MB', 'CL63AMG', ' - CL63 AMG'),
('MB', 'CL65AMG', ' - CL65 AMG'),
('MB', 'CLK_CLASS', 'CLK Class (7)'),
('MB', 'CLK320', ' - CLK320'),
('MB', 'CLK350', ' - CLK350'),
('MB', 'CLK430', ' - CLK430'),
('MB', 'CLK500', ' - CLK500'),
('MB', 'CLK550', ' - CLK550'),
('MB', 'CLK55AMG', ' - CLK55 AMG'),
('MB', 'CLK63AMG', ' - CLK63 AMG'),
('MB', 'CLS_CLASS', 'CLS Class (4)'),
('MB', 'CLS500', ' - CLS500'),
('MB', 'CLS550', ' - CLS550'),
('MB', 'CLS55AMG', ' - CLS55 AMG'),
('MB', 'CLS63AMG', ' - CLS63 AMG'),
('MB', 'E_CLASS', 'E Class (18)'),
('MB', '260E', ' - 260E'),
('MB', '280CE', ' - 280CE'),
('MB', '280E', ' - 280E'),
('MB', '400E', ' - 400E'),
('MB', '500E', ' - 500E'),
('MB', 'E300', ' - E300'),
('MB', 'E320', ' - E320'),
('MB', 'E320BLUE', ' - E320 Bluetec'),
('MB', 'E320CDI', ' - E320 CDI'),
('MB', 'E350', ' - E350'),
('MB', 'E350BLUE', ' - E350 Bluetec'),
('MB', 'E400', ' - E400 Hybrid'),
('MB', 'E420', ' - E420'),
('MB', 'E430', ' - E430'),
('MB', 'E500', ' - E500'),
('MB', 'E550', ' - E550'),
('MB', 'E55AMG', ' - E55 AMG'),
('MB', 'E63AMG', ' - E63 AMG'),
('MB', 'G_CLASS', 'G Class (4)'),
('MB', 'G500', ' - G500'),
('MB', 'G550', ' - G550'),
('MB', 'G55AMG', ' - G55 AMG'),
('MB', 'G63AMG', ' - G63 AMG'),
('MB', 'GL_CLASS', 'GL Class (5)'),
('MB', 'GL320BLUE', ' - GL320 Bluetec'),
('MB', 'GL320CDI', ' - GL320 CDI'),
('MB', 'GL350BLUE', ' - GL350 Bluetec'),
('MB', 'GL450', ' - GL450'),
('MB', 'GL550', ' - GL550'),
('MB', 'GLK_CLASS', 'GLK Class (1)'),
('MB', 'GLK350', ' - GLK350'),
('MB', 'M_CLASS', 'M Class (11)'),
('MB', 'ML320', ' - ML320'),
('MB', 'ML320BLUE', ' - ML320 Bluetec'),
('MB', 'ML320CDI', ' - ML320 CDI'),
('MB', 'ML350', ' - ML350'),
('MB', 'ML350BLUE', ' - ML350 Bluetec'),
('MB', 'ML430', ' - ML430'),
('MB', 'ML450HY', ' - ML450 Hybrid'),
('MB', 'ML500', ' - ML500'),
('MB', 'ML550', ' - ML550'),
('MB', 'ML55AMG', ' - ML55 AMG'),
('MB', 'ML63AMG', ' - ML63 AMG'),
('MB', 'R_CLASS', 'R Class (6)'),
('MB', 'R320BLUE', ' - R320 Bluetec'),
('MB', 'R320CDI', ' - R320 CDI'),
('MB', 'R350', ' - R350'),
('MB', 'R350BLUE', ' - R350 Bluetec'),
('MB', 'R500', ' - R500'),
('MB', 'R63AMG', ' - R63 AMG'),
('MB', 'S_CLASS', 'S Class (30)'),
('MB', '300SD', ' - 300SD'),
('MB', '300SDL', ' - 300SDL'),
('MB', '300SE', ' - 300SE'),
('MB', '300SEL', ' - 300SEL'),
('MB', '350SD', ' - 350SD'),
('MB', '350SDL', ' - 350SDL'),
('MB', '380SE', ' - 380SE'),
('MB', '380SEC', ' - 380SEC'),
('MB', '380SEL', ' - 380SEL'),
('MB', '400SE', ' - 400SE'),
('MB', '400SEL', ' - 400SEL'),
('MB', '420SEL', ' - 420SEL'),
('MB', '500SEC', ' - 500SEC'),
('MB', '500SEL', ' - 500SEL'),
('MB', '560SEC', ' - 560SEC'),
('MB', '560SEL', ' - 560SEL'),
('MB', '600SEC', ' - 600SEC'),
('MB', '600SEL', ' - 600SEL'),
('MB', 'S320', ' - S320'),
('MB', 'S350', ' - S350'),
('MB', 'S350BLUE', ' - S350 Bluetec'),
('MB', 'S400HY', ' - S400 Hybrid'),
('MB', 'S420', ' - S420'),
('MB', 'S430', ' - S430'),
('MB', 'S500', ' - S500'),
('MB', 'S550', ' - S550'),
('MB', 'S55AMG', ' - S55 AMG'),
('MB', 'S600', ' - S600'),
('MB', 'S63AMG', ' - S63 AMG'),
('MB', 'S65AMG', ' - S65 AMG'),
('MB', 'SL_CLASS', 'SL Class (13)'),
('MB', '300SL', ' - 300SL'),
('MB', '380SL', ' - 380SL'),
('MB', '380SLC', ' - 380SLC'),
('MB', '500SL', ' - 500SL'),
('MB', '560SL', ' - 560SL'),
('MB', '600SL', ' - 600SL'),
('MB', 'SL320', ' - SL320'),
('MB', 'SL500', ' - SL500'),
('MB', 'SL550', ' - SL550'),
('MB', 'SL55AMG', ' - SL55 AMG'),
('MB', 'SL600', ' - SL600'),
('MB', 'SL63AMG', ' - SL63 AMG'),
('MB', 'SL65AMG', ' - SL65 AMG'),
('MB', 'SLK_CLASS', 'SLK Class (8)'),
('MB', 'SLK230', ' - SLK230'),
('MB', 'SLK250', ' - SLK250'),
('MB', 'SLK280', ' - SLK280'),
('MB', 'SLK300', ' - SLK300'),
('MB', 'SLK320', ' - SLK320'),
('MB', 'SLK32AMG', ' - SLK32 AMG'),
('MB', 'SLK350', ' - SLK350'),
('MB', 'SLK55AMG', ' - SLK55 AMG'),
('MB', 'SLR_CLASS', 'SLR Class (1)'),
('MB', 'SLR', ' - SLR'),
('MB', 'SLS_CLASS', 'SLS Class (1)'),
('MB', 'SLSAMG', ' - SLS AMG'),
('MB', 'SPRINTER_CLASS', 'Sprinter Class (1)'),
('MB', 'MBSPRINTER', ' - Sprinter'),
('MB', 'MBOTH', 'Other Mercedes-Benz Models'),
('MERC', 'CAPRI', 'Capri'),
('MERC', 'COUGAR', 'Cougar'),
('MERC', 'MERCGRAND', 'Grand Marquis'),
('MERC', 'LYNX', 'Lynx'),
('MERC', 'MARAUDER', 'Marauder'),
('MERC', 'MARINER', 'Mariner'),
('MERC', 'MARQ', 'Marquis'),
('MERC', 'MILAN', 'Milan'),
('MERC', 'MONTEGO', 'Montego'),
('MERC', 'MONTEREY', 'Monterey'),
('MERC', 'MOUNTA', 'Mountaineer'),
('MERC', 'MYSTIQ', 'Mystique'),
('MERC', 'SABLE', 'Sable'),
('MERC', 'TOPAZ', 'Topaz'),
('MERC', 'TRACER', 'Tracer'),
('MERC', 'VILLA', 'Villager'),
('MERC', 'MERCZEP', 'Zephyr'),
('MERC', 'MEOTH', 'Other Mercury Models'),
('MERKUR', 'SCORP', 'Scorpio'),
('MERKUR', 'XR4TI', 'XR4Ti'),
('MERKUR', 'MEROTH', 'Other Merkur Models'),
('MINI', 'COOPRCLUB_MODELS', 'Cooper Clubman Models (2)'),
('MINI', 'COOPERCLUB', ' - Cooper Clubman'),
('MINI', 'COOPRCLUBS', ' - Cooper S Clubman'),
('MINI', 'COOPCOUNTRY_MODELS', 'Cooper Countryman Models (2)'),
('MINI', 'COUNTRYMAN', ' - Cooper Countryman'),
('MINI', 'COUNTRYMNS', ' - Cooper S Countryman'),
('MINI', 'COOPCOUP_MODELS', 'Cooper Coupe Models (2)'),
('MINI', 'MINICOUPE', ' - Cooper Coupe'),
('MINI', 'MINISCOUPE', ' - Cooper S Coupe'),
('MINI', 'COOPER_MODELS', 'Cooper Models (2)'),
('MINI', 'COOPER', ' - Cooper'),
('MINI', 'COOPERS', ' - Cooper S'),
('MINI', 'COOPRROAD_MODELS', 'Cooper Roadster Models (2)'),
('MINI', 'COOPERROAD', ' - Cooper Roadster'),
('MINI', 'COOPERSRD', ' - Cooper S Roadster'),
('MIT', '3000GT', '3000GT'),
('MIT', 'CORD', 'Cordia'),
('MIT', 'DIAMAN', 'Diamante'),
('MIT', 'ECLIP', 'Eclipse'),
('MIT', 'ENDEAVOR', 'Endeavor'),
('MIT', 'MITEXP', 'Expo'),
('MIT', 'GALANT', 'Galant'),
('MIT', 'MITI', 'i'),
('MIT', 'LANCERMITS', 'Lancer'),
('MIT', 'LANCEREVO', 'Lancer Evolution'),
('MIT', 'MITPU', 'Mighty Max'),
('MIT', 'MIRAGE', 'Mirage'),
('MIT', 'MONT', 'Montero'),
('MIT', 'MONTSPORT', 'Montero Sport'),
('MIT', 'OUTLANDER', 'Outlander'),
('MIT', 'OUTLANDSPT', 'Outlander Sport'),
('MIT', 'PRECIS', 'Precis'),
('MIT', 'RAIDERMITS', 'Raider'),
('MIT', 'SIGMA', 'Sigma'),
('MIT', 'MITSTAR', 'Starion'),
('MIT', 'TRED', 'Tredia'),
('MIT', 'MITVAN', 'Van'),
('MIT', 'MITOTH', 'Other Mitsubishi Models'),
('NISSAN', 'NIS200SX', '200SX'),
('NISSAN', '240SX', '240SX'),
('NISSAN', '300ZXTURBO', '300ZX'),
('NISSAN', '350Z', '350Z'),
('NISSAN', '370Z', '370Z'),
('NISSAN', 'ALTIMA', 'Altima'),
('NISSAN', 'PATHARMADA', 'Armada'),
('NISSAN', 'AXXESS', 'Axxess'),
('NISSAN', 'CUBE', 'Cube'),
('NISSAN', 'FRONTI', 'Frontier'),
('NISSAN', 'GT-R', 'GT-R'),
('NISSAN', 'JUKE', 'Juke'),
('NISSAN', 'LEAF', 'Leaf'),
('NISSAN', 'MAX', 'Maxima'),
('NISSAN', 'MURANO', 'Murano'),
('NISSAN', 'MURANOCROS', 'Murano CrossCabriolet'),
('NISSAN', 'NV', 'NV'),
('NISSAN', 'NX', 'NX'),
('NISSAN', 'PATH', 'Pathfinder'),
('NISSAN', 'NISPU', 'Pickup'),
('NISSAN', 'PULSAR', 'Pulsar'),
('NISSAN', 'QUEST', 'Quest'),
('NISSAN', 'ROGUE', 'Rogue'),
('NISSAN', 'SENTRA', 'Sentra'),
('NISSAN', 'STANZA', 'Stanza'),
('NISSAN', 'TITAN', 'Titan'),
('NISSAN', 'NISVAN', 'Van'),
('NISSAN', 'VERSA', 'Versa'),
('NISSAN', 'XTERRA', 'Xterra'),
('NISSAN', 'NISSOTH', 'Other Nissan Models'),
('OLDS', '88', '88'),
('OLDS', 'ACHIEV', 'Achieva'),
('OLDS', 'ALERO', 'Alero'),
('OLDS', 'AURORA', 'Aurora'),
('OLDS', 'BRAV', 'Bravada'),
('OLDS', 'CUCR', 'Custom Cruiser'),
('OLDS', 'OLDCUS', 'Cutlass'),
('OLDS', 'OLDCALAIS', 'Cutlass Calais'),
('OLDS', 'CIERA', 'Cutlass Ciera'),
('OLDS', 'CSUPR', 'Cutlass Supreme'),
('OLDS', 'OLDSFIR', 'Firenza'),
('OLDS', 'INTRIG', 'Intrigue'),
('OLDS', '98', 'Ninety-Eight'),
('OLDS', 'OMEG', 'Omega'),
('OLDS', 'REGEN', 'Regency'),
('OLDS', 'SILHO', 'Silhouette'),
('OLDS', 'TORO', 'Toronado'),
('OLDS', 'OLDOTH', 'Other Oldsmobile Models'),
('PEUG', '405', '405'),
('PEUG', '504', '504'),
('PEUG', '505', '505'),
('PEUG', '604', '604'),
('PEUG', 'UNAVAILPEU', 'Other Peugeot Models'),
('PLYM', 'ACC', 'Acclaim'),
('PLYM', 'ARROW', 'Arrow'),
('PLYM', 'BREEZE', 'Breeze'),
('PLYM', 'CARAVE', 'Caravelle'),
('PLYM', 'CHAMP', 'Champ'),
('PLYM', 'COLT', 'Colt'),
('PLYM', 'PLYMCONQ', 'Conquest'),
('PLYM', 'GRANFURY', 'Gran Fury'),
('PLYM', 'PLYMGRANV', 'Grand Voyager'),
('PLYM', 'HORI', 'Horizon'),
('PLYM', 'LASER', 'Laser'),
('PLYM', 'NEON', 'Neon'),
('PLYM', 'PROWLE', 'Prowler'),
('PLYM', 'RELI', 'Reliant'),
('PLYM', 'SAPPOROPLY', 'Sapporo'),
('PLYM', 'SCAMP', 'Scamp'),
('PLYM', 'SUNDAN', 'Sundance'),
('PLYM', 'TRAILDUST', 'Trailduster'),
('PLYM', 'VOYA', 'Voyager'),
('PLYM', 'PLYOTH', 'Other Plymouth Models'),
('PONT', 'T-1000', '1000'),
('PONT', '6000', '6000'),
('PONT', 'AZTEK', 'Aztek'),
('PONT', 'BON', 'Bonneville'),
('PONT', 'CATALINA', 'Catalina'),
('PONT', 'FIERO', 'Fiero'),
('PONT', 'FBIRD', 'Firebird'),
('PONT', 'G3', 'G3'),
('PONT', 'G5', 'G5'),
('PONT', 'G6', 'G6'),
('PONT', 'G8', 'G8'),
('PONT', 'GRNDAM', 'Grand Am'),
('PONT', 'GP', 'Grand Prix'),
('PONT', 'GTO', 'GTO'),
('PONT', 'J2000', 'J2000'),
('PONT', 'LEMANS', 'Le Mans'),
('PONT', 'MONTANA', 'Montana'),
('PONT', 'PARISI', 'Parisienne'),
('PONT', 'PHOENIX', 'Phoenix'),
('PONT', 'SAFARIPONT', 'Safari'),
('PONT', 'SOLSTICE', 'Solstice'),
('PONT', 'SUNBIR', 'Sunbird'),
('PONT', 'SUNFIR', 'Sunfire'),
('PONT', 'TORRENT', 'Torrent'),
('PONT', 'TS', 'Trans Sport'),
('PONT', 'VIBE', 'Vibe'),
('PONT', 'PONOTH', 'Other Pontiac Models'),
('POR', '911', '911'),
('POR', '924', '924'),
('POR', '928', '928'),
('POR', '944', '944'),
('POR', '968', '968'),
('POR', 'BOXSTE', 'Boxster'),
('POR', 'CARRERAGT', 'Carrera GT'),
('POR', 'CAYENNE', 'Cayenne'),
('POR', 'CAYMAN', 'Cayman'),
('POR', 'PANAMERA', 'Panamera'),
('POR', 'POROTH', 'Other Porsche Models'),
('RAM', 'RAM2504WD', '1500'),
('RAM', 'RAM35002WD', '2500'),
('RAM', 'RAM4502WD', '3500'),
('RAM', 'RAM5500', '4500'),
('REN', '18I', '18i'),
('REN', 'FU', 'Fuego'),
('REN', 'LECAR', 'Le Car'),
('REN', 'R18', 'R18'),
('REN', 'RENSPORT', 'Sportwagon'),
('REN', 'UNAVAILREN', 'Other Renault Models'),
('RR', 'CAMAR', 'Camargue'),
('RR', 'CORN', 'Corniche'),
('RR', 'GHOST', 'Ghost'),
('RR', 'PARKWARD', 'Park Ward'),
('RR', 'PHANT', 'Phantom'),
('RR', 'DAWN', 'Silver Dawn'),
('RR', 'SILSERAPH', 'Silver Seraph'),
('RR', 'RRSPIR', 'Silver Spirit'),
('RR', 'SPUR', 'Silver Spur'),
('RR', 'UNAVAILRR', 'Other Rolls-Royce Models'),
('SAAB', '9-2X', '9-2X'),
('SAAB', '9-3', '9-3'),
('SAAB', '9-4X', '9-4X'),
('SAAB', '9-5', '9-5'),
('SAAB', '97X', '9-7X'),
('SAAB', '900', '900'),
('SAAB', '9000', '9000'),
('SAAB', 'SAOTH', 'Other Saab Models'),
('SATURN', 'ASTRA', 'Astra'),
('SATURN', 'AURA', 'Aura'),
('SATURN', 'ION', 'ION'),
('SATURN', 'L_SERIES', 'L Series (3)'),
('SATURN', 'L100', ' - L100'),
('SATURN', 'L200', ' - L200'),
('SATURN', 'L300', ' - L300'),
('SATURN', 'LSSATURN', 'LS'),
('SATURN', 'LW_SERIES', 'LW Series (4)'),
('SATURN', 'LW', ' - LW1'),
('SATURN', 'LW2', ' - LW2'),
('SATURN', 'LW200', ' - LW200'),
('SATURN', 'LW300', ' - LW300'),
('SATURN', 'OUTLOOK', 'Outlook'),
('SATURN', 'RELAY', 'Relay'),
('SATURN', 'SC_SERIES', 'SC Series (2)'),
('SATURN', 'SC1', ' - SC1'),
('SATURN', 'SC2', ' - SC2'),
('SATURN', 'SKY', 'Sky'),
('SATURN', 'SL_SERIES', 'SL Series (3)'),
('SATURN', 'SL', ' - SL'),
('SATURN', 'SL1', ' - SL1'),
('SATURN', 'SL2', ' - SL2'),
('SATURN', 'SW_SERIES', 'SW Series (2)'),
('SATURN', 'SW1', ' - SW1'),
('SATURN', 'SW2', ' - SW2'),
('SATURN', 'VUE', 'Vue'),
('SATURN', 'SATOTH', 'Other Saturn Models'),
('SCION', 'SCIFRS', 'FR-S'),
('SCION', 'IQ', 'iQ'),
('SCION', 'TC', 'tC'),
('SCION', 'XA', 'xA'),
('SCION', 'XB', 'xB'),
('SCION', 'XD', 'xD'),
('SMART', 'FORTWO', 'fortwo'),
('SMART', 'SMOTH', 'Other smart Models'),
('SRT', 'SRTVIPER', 'Viper'),
('STERL', '825', '825'),
('STERL', '827', '827'),
('STERL', 'UNAVAILSTE', 'Other Sterling Models'),
('SUB', 'BAJA', 'Baja'),
('SUB', 'BRAT', 'Brat'),
('SUB', 'SUBBRZ', 'BRZ'),
('SUB', 'FOREST', 'Forester'),
('SUB', 'IMPREZ', 'Impreza'),
('SUB', 'IMPWRX', 'Impreza WRX'),
('SUB', 'JUSTY', 'Justy'),
('SUB', 'SUBL', 'L Series'),
('SUB', 'LEGACY', 'Legacy'),
('SUB', 'LOYALE', 'Loyale'),
('SUB', 'SUBOUTBK', 'Outback'),
('SUB', 'SVX', 'SVX'),
('SUB', 'B9TRIBECA', 'Tribeca'),
('SUB', 'XT', 'XT'),
('SUB', 'XVCRSSTREK', 'XV Crosstrek'),
('SUB', 'SUBOTH', 'Other Subaru Models'),
('SUZUKI', 'AERIO', 'Aerio'),
('SUZUKI', 'EQUATOR', 'Equator'),
('SUZUKI', 'ESTEEM', 'Esteem'),
('SUZUKI', 'FORENZA', 'Forenza'),
('SUZUKI', 'GRANDV', 'Grand Vitara'),
('SUZUKI', 'KIZASHI', 'Kizashi'),
('SUZUKI', 'RENO', 'Reno'),
('SUZUKI', 'SAMUR', 'Samurai'),
('SUZUKI', 'SIDE', 'Sidekick'),
('SUZUKI', 'SWIFT', 'Swift'),
('SUZUKI', 'SX4', 'SX4'),
('SUZUKI', 'VERONA', 'Verona'),
('SUZUKI', 'VITARA', 'Vitara'),
('SUZUKI', 'X90', 'X-90'),
('SUZUKI', 'XL7', 'XL7'),
('SUZUKI', 'SUZOTH', 'Other Suzuki Models'),
('TESLA', 'ROADSTER', 'Roadster'),
('TOYOTA', '4RUN', '4Runner'),
('TOYOTA', 'AVALON', 'Avalon'),
('TOYOTA', 'CAMRY', 'Camry'),
('TOYOTA', 'CELICA', 'Celica'),
('TOYOTA', 'COROL', 'Corolla'),
('TOYOTA', 'CORONA', 'Corona'),
('TOYOTA', 'CRESS', 'Cressida'),
('TOYOTA', 'ECHO', 'Echo'),
('TOYOTA', 'FJCRUIS', 'FJ Cruiser'),
('TOYOTA', 'HIGHLANDER', 'Highlander'),
('TOYOTA', 'LC', 'Land Cruiser'),
('TOYOTA', 'MATRIX', 'Matrix'),
('TOYOTA', 'MR2', 'MR2'),
('TOYOTA', 'MR2SPYDR', 'MR2 Spyder'),
('TOYOTA', 'PASEO', 'Paseo'),
('TOYOTA', 'PICKUP', 'Pickup'),
('TOYOTA', 'PREVIA', 'Previa'),
('TOYOTA', 'PRIUS', 'Prius'),
('TOYOTA', 'PRIUSC', 'Prius C'),
('TOYOTA', 'PRIUSV', 'Prius V'),
('TOYOTA', 'RAV4', 'RAV4'),
('TOYOTA', 'SEQUOIA', 'Sequoia'),
('TOYOTA', 'SIENNA', 'Sienna'),
('TOYOTA', 'SOLARA', 'Solara'),
('TOYOTA', 'STARLET', 'Starlet'),
('TOYOTA', 'SUPRA', 'Supra'),
('TOYOTA', 'T100', 'T100'),
('TOYOTA', 'TACOMA', 'Tacoma'),
('TOYOTA', 'TERCEL', 'Tercel'),
('TOYOTA', 'TUNDRA', 'Tundra'),
('TOYOTA', 'TOYVAN', 'Van'),
('TOYOTA', 'VENZA', 'Venza'),
('TOYOTA', 'YARIS', 'Yaris'),
('TOYOTA', 'TOYOTH', 'Other Toyota Models'),
('TRI', 'TR7', 'TR7'),
('TRI', 'TR8', 'TR8'),
('TRI', 'TRIOTH', 'Other Triumph Models'),
('VOLKS', 'BEETLE', 'Beetle'),
('VOLKS', 'VOLKSCAB', 'Cabrio'),
('VOLKS', 'CAB', 'Cabriolet'),
('VOLKS', 'CC', 'CC'),
('VOLKS', 'CORR', 'Corrado'),
('VOLKS', 'DASHER', 'Dasher'),
('VOLKS', 'EOS', 'Eos'),
('VOLKS', 'EUROVAN', 'Eurovan'),
('VOLKS', 'VOLKSFOX', 'Fox'),
('VOLKS', 'GLI', 'GLI'),
('VOLKS', 'GOLFR', 'Golf R'),
('VOLKS', 'GTI', 'GTI'),
('VOLKS', 'GOLFANDRABBITMODELS', 'Golf and Rabbit Models (2)'),
('VOLKS', 'GOLF', ' - Golf'),
('VOLKS', 'RABBIT', ' - Rabbit'),
('VOLKS', 'JET', 'Jetta'),
('VOLKS', 'PASS', 'Passat'),
('VOLKS', 'PHAETON', 'Phaeton'),
('VOLKS', 'RABBITPU', 'Pickup'),
('VOLKS', 'QUAN', 'Quantum'),
('VOLKS', 'R32', 'R32'),
('VOLKS', 'ROUTAN', 'Routan'),
('VOLKS', 'SCIR', 'Scirocco'),
('VOLKS', 'TIGUAN', 'Tiguan'),
('VOLKS', 'TOUAREG', 'Touareg'),
('VOLKS', 'VANAG', 'Vanagon'),
('VOLKS', 'VWOTH', 'Other Volkswagen Models'),
('VOLVO', '240', '240'),
('VOLVO', '260', '260'),
('VOLVO', '740', '740'),
('VOLVO', '760', '760'),
('VOLVO', '780', '780'),
('VOLVO', '850', '850'),
('VOLVO', '940', '940'),
('VOLVO', '960', '960'),
('VOLVO', 'C30', 'C30'),
('VOLVO', 'C70', 'C70'),
('VOLVO', 'S40', 'S40'),
('VOLVO', 'S60', 'S60'),
('VOLVO', 'S70', 'S70'),
('VOLVO', 'S80', 'S80'),
('VOLVO', 'S90', 'S90'),
('VOLVO', 'V40', 'V40'),
('VOLVO', 'V50', 'V50'),
('VOLVO', 'V70', 'V70'),
('VOLVO', 'V90', 'V90'),
('VOLVO', 'XC60', 'XC60'),
('VOLVO', 'XC', 'XC70'),
('VOLVO', 'XC90', 'XC90'),
('VOLVO', 'VOLOTH', 'Other Volvo Models'),
('YUGO', 'GV', 'GV'),
('YUGO', 'GVC', 'GVC'),
('YUGO', 'GVL', 'GVL'),
('YUGO', 'GVS', 'GVS'),
('YUGO', 'GVX', 'GVX'),
('YUGO', 'YUOTH', 'Other Yugo Models');
