DROP TABLE IF EXISTS car_warehouse;

CREATE TABLE car_warehouse (
  id SERIAL NOT NULL ,
  owner_id NUMERIC(8,0) REFERENCES customers(afm),
  plate PLATE_NUM UNIQUE,
  model_id VARCHAR(20) NOT NULL REFERENCES car_models(id),
  manufacturing_date NUMERIC(4,0),
  condition CAR_CONDITION NOT NULL,

  PRIMARY KEY (id)
);

DELETE FROM care_warehouse;

insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (76954758, ROW('LTS', '6048'), 'S4', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (13927211, ROW('GFD', '0377'), 'VANQUISH', 1989, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RS4', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (29841167, ROW('TJJ', '3335'), 'V12VANT', 2007, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (13927211, ROW('ZGS', '8376'), 'VIGOR', 2013, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'A6', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (31000098, ROW('IMN', '9488'), '3.2CL', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (22800321, ROW('XPK', '6870'), 'MDX', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'EAGLE', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (36707298, ROW('DXE', '1904'), 'RS4', 1996, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (29192792, ROW('RNF', '4991'), 'SPID', 1999, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (14067861, ROW('GXC', '1487'), 'AUDI200', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '90', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (87952992, ROW('HQX', '5954'), 'INTEG', 1999, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (20198730, ROW('VTQ', '3773'), '4000', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (68145155, ROW('DTH', '2011'), 'VANQUISH', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (21307338, ROW('CRN', '5188'), 'NSX', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RDX', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'AUDI100', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (28212729, ROW('KII', '7893'), 'A3', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'S4', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '2.2CL', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RS4', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (22555822, ROW('EOB', '6043'), '2.2CL', 1994, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (56319863, ROW('MIB', '4753'), 'DB7', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (99407021, ROW('PXV', '6813'), 'CL_MODELS', 1993, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RS4', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (43377841, ROW('VWU', '0912'), 'AMCALLIAN', 2005, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (96427477, ROW('BSR', '3258'), '4000', 2009, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VANQUISH', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (70505173, ROW('EMJ', '6536'), 'TL_MODELS', 1997, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '80', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (66405654, ROW('NSX', '6420'), 'VIRAGE', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (61524414, ROW('PSM', '3667'), 'LEGEND', 1997, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'V12VANT', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'ALLRDQUA', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'TL_MODELS', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (11056144, ROW('ANX', '7648'), '3.2CL', 2004, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (97794267, ROW('KFY', '0596'), 'VANQUISH', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RL_MODELS', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (66310235, ROW('BJK', '3969'), 'A7', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LAGONDA', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (49238354, ROW('XCB', '0916'), 'RL_MODELS', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (71422663, ROW('SWX', '0144'), 'VANQUISH', 2006, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (23963684, ROW('XWV', '9116'), 'RDX', 2006, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (16004661, ROW('PLL', '6697'), 'LEGEND', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'Q7', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (58083344, ROW('PGQ', '9770'),'NSX', 1986, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (57771710, ROW('HZN', '1833'), 'VIRAGE', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (90619321, ROW('LRQ', '4197'), '4000', 2007, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (96842398, ROW('XTD', '6467'), 'VIGOR', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'MDX', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (59548136, ROW('RJM', '5153'), '3.2TL', 2004, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (29278406, ROW('PJV', '3446'), 'ALLRDQUA', 1999, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (24122494, ROW('URY', '9698'), 'AMCENC', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (91134454, ROW('DGU', '4213'), 'QUATTR', 2004, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (96443428, ROW('PPQ', '4836'), 'A8', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (68167178, ROW('YOB', '7838'), 'RAPIDE', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RDX', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (89143769, ROW('PAP', '3679'), 'VANQUISH', 1991, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'NSX', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (14067861, ROW('AXP', '0263'), 'LAGONDA', 2009, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VANQUISH', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'A4', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (24122494, ROW('QFO', '8058'),'V12VANT', 2005, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (53792806, ROW('GJB', '0678'), 'CL_MODELS', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (87432145, ROW('KFW', '7279'), 'LEGEND', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (42580813, ROW('VHY', '7436'), 'RS4', 1993, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '90', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (96333693, ROW('YSI', '6149'), 'AMCSPIRIT', 2004, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (54843263, ROW('IBB', '2325'), '3.2CL', 2006, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (29126064, ROW('DEX', '0727'), 'ALFA8C', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (25316280, ROW('KEP', '4992'), 'VIGOR', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '4000', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'CL_MODELS', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (60779813, ROW('DOV', '8904'), 'VANQUISH', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (16656312, ROW('FVI', '6976'), 'Q5', 1991, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (76915724, ROW('BTK', '5807'), 'RS6', 1980, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (17845019, ROW('GZN', '9430'), 'QUATTR', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (81359559, ROW('TKL', '7378'), 'TL_MODELS', 2011, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (91476709, ROW('VPF', '6967'), 'A8', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'CON', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (60944185, ROW('IAO', '5394'), 'DB7', 2003, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (42580813, ROW('HPN', '8060'),'NSX', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (43979748, ROW('VXA', '8677'), 'MDX', 1996, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (43377841, ROW('GMV', '6096'), 'A4', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'ALLRDQUA', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'EAGLE', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (23963684, ROW('BUG', '3766'), 'RSX', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (72839037, ROW('VTD', '4608'), 'AMCENC', 2011, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RL_MODELS', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (44353279, ROW('BZK', '6149'), 'TL', 2009, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VANQUISH', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (99065196, ROW('ZBH', '0932'), 'VANQUISH', 1985, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VANQUISH', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VANQUISH', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (82449373, ROW('RBA', '5360'), 'RDX', 1996, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (25316280, ROW('UGM', '7331'), 'VANQUISH', 1997, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (58489770, ROW('MQM', '6358'), 'LEGEND', 2011, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (87176931, ROW('XEI', '2383'), '4000', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (31949528, ROW('FGG', '5001'), 'RAPIDE', 2005, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (61357425, ROW('IFB', '4375'), 'AUDI100', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'DB7', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'TL_MODELS', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (97794267, ROW('BCG', '0971'), 'VANQUISH', 1973, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (41090503, ROW('UZF', '8018'), '4000', 1991, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (31350635, ROW('KJG', '5524'), 'A7', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (77867161, ROW('YUA', '3965'), 'SPID', 1987, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (55922039, ROW('ZIZ', '2668'), '5000', 1999, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (81892680, ROW('SLY', '1564'), 'LEGEND', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (16758758, ROW('HER', '7075'), '90', 2011, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RDX', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (42558959, ROW('CTA', '9707'), 'ALFA164', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (93473447, ROW('UDI', '8999'), 'SLX', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (62679754, ROW('VCK', '9703'), 'VANQUISH', 1999, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VANQUISH', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (42141880, ROW('EGP', '1313'), 'DB7', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (76915724, ROW('OON', '4321'), '2.2CL', 1996, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (19010516, ROW('OTU', '1302'), 'ALFA8C', 1985, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (71215689, ROW('NUG', '8667'), 'ALFA164', 1996, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (86693951, ROW('NHQ', '1418'), 'RS6', 1990, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (69850336, ROW('TKS', '8508'), 'ILX', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (65492779, ROW('GNL', '4362'), 'A3', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (37614068, ROW('MYS', '7706'), 'VANQUISH', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (76537521, ROW('KWR', '5554'), 'TL_MODELS', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'MIL', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (34393972, ROW('UZX', '5426'), 'AZURE', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (86927213, ROW('UHV', '0126'), 'VANQUISH', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (69850336, ROW('XBB', '1746'), 'V12VANT', 2009, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (31762764, ROW('KIG', '6751'), 'VANQUISH', 2011, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'X1', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (94586793, ROW('RAC', '9519'), 'MDX', 1993, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (26656937, ROW('FSN', '7636'), 'FERCALIF', 2007, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'EDGE', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'FOCUS', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VIRAGE', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'ALFA164', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'CRV', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'A7', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (53529901, ROW('QMY', '4981'), 'RDX', 1986, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (31000098, ROW('BUC', '8666'), 'VANQUISH', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (54286340, ROW('HKK', '2851'), 'A8', 2009, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (91134454, ROW('WTC', '5238'), 'VANQUISH', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (19165232, ROW('UYX', '1386'), 'VIGOR', 1989, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (15791033, ROW('GQY', '4923'), 'VANQUISH', 2006, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (17571532, ROW('NGV', '2527'), 'ILX', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (21468518, ROW('TTC', '5966'), 'VANQUISH', 2009, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'CON', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (68145155, ROW('XFS', '1986'), 'RS4', 2003, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (79075137, ROW('IIL', '3634'), 'XKR', 1993, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (52447846, ROW('OBT', '3012'), 'LAGONDA', 2005, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VIGOR', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (12312715, ROW('JXG', '3231'),'NSX', 1997, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (86929394, ROW('TMU', '7939'), 'RDX', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (30886727, ROW('SLU', '9032'), 'MIL', 1997, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (70075533, ROW('RTF', '0088'), '4000', 1996, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (90255936, ROW('BPY', '3943'), 'VIGOR', 1985, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (27448715, ROW('IES', '2946'), 'RS4', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'AZURE', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (29226869, ROW('YAQ', '4865'), 'RS4', 2011, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (52312844, ROW('LQE', '6397'), 'ILX', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (56482586, ROW('ETC', '4084'), 'FERCALIF', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (66405654, ROW('HUA', '8649'), 'TL_MODELS', 1999, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (78167564, ROW('HJL', '3257'), 'AVENT', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (72048054, ROW('SPH', '5206'), '3.2CL', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (53079457, ROW('GXQ', '8990'), '4000', 2011, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RS4', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (77370632, ROW('QLD', '9328'), 'XKR', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '5000', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '3.2CL', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (12497847, ROW('ZTG', '6821'), 'RDX', 1994, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (26693614, ROW('XZR', '1880'), 'VANQUISH', 2011, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (42199909, ROW('XTS', '3352'), 'V12VANT', 2006, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (75568572, ROW('JSH', '3504'), 'RDX', 2004, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (34393972, ROW('UZW', '3813'), 'ALFA164', 2004, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (26692799, ROW('CJT', '6903'), '3.2TL', 2004, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (90255936, ROW('MJQ', '9342'), '4000', 2006, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '3.2CL', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (59548136, ROW('HMZ', '9910'), 'ALFA164', 2003, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'V12VANT', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'FOCUS', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (46252241, ROW('UDE', '5915'), 'GALLARDO', 2003, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (61619852, ROW('VPZ', '3820'), 'ALLRDQUA', 1993, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (17845019, ROW('HSY', '7118'), '3.2TL', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (95290933, ROW('EKJ', '9533'),'NSX', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (69984930, ROW('QKZ', '2857'), 'X1', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (11525951, ROW('DFQ', '5803'), 'NSX', 2003, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (66881466, ROW('ALD', '5322'), 'VANQUISH', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RDX', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (53529901, ROW('HSN', '6553'), '3.2TL', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'DEFEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'EVOQUE', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (17571532, ROW('XOP', '2193'), 'LEGEND', 2009, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (69741163, ROW('KZZ', '1441'), 'LEGEND', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (76610326, ROW('TFJ', '9918'), 'RSX', 1993, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (28212729, ROW('FDW', '8154'), '4000', 1993, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (90255936, ROW('LKN', '8597'), '4000', 1996, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (52312844, ROW('SCI', '8118'), 'ES250', 1985, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (29204016, ROW('KGE', '3385'), '3.2CL', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RSX', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (31651931, ROW('DKW', '4384'), 'V12VANT', 1994, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (55922039, ROW('BQD', '3094'), 'CON', 1994, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (39963076, ROW('UYF', '4733'), 'VANQUISH', 2004, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (41238491, ROW('GUV', '4860'), 'LEGEND', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (66880490, ROW('KCW', '0197'), 'LEGEND', 1987, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (86772968, ROW('GZD', '6516'), 'LEGEND', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (94098465, ROW('NJY', '2226'), 'V12VANT', 1985, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (12865550, ROW('WKB', '8416'), 'VIRAGE', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (90619321, ROW('YSR', '4400'), 'CL_MODELS', 2006, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (74480550, ROW('PMX', '7243'), 'S4', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (65664820, ROW('YOF', '4624'), 'LEGEND', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (72071195, ROW('RCM', '1114'), 'VANQUISH', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (62483389, ROW('ZWY', '5230'), 'NSX', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (95378109, ROW('ZGY', '0793'), 'EVORA', 1997, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (96253405, ROW('QRU', '0643'), 'ALFA8C', 1985, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (15999676, ROW('IML', '1800'), 'DB7', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VIGOR', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (85170044, ROW('GAW', '8854'), 'V12VANT', 2006, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (87176931, ROW('LOV', '2626'), 'S4', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'BITRBO', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (24471750, ROW('XKK', '1765'), 'ALFA164', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (39496641, ROW('RGK', '2840'), 'SPID', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (49238354, ROW('PGR', '0155'), 'ALLRDQUA', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (37694232, ROW('WXT', '4326'), 'GRANSPORT', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'MIL', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (52970865, ROW('LYL', '5802'), 'DB7', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (47545979, ROW('QVW', '8832'), 'MP4', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (11856678, ROW('ERV', '4251'), 'CRV', 2007, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RS4', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (89808279, ROW('DMS', '5288'), 'VANQUISH', 2003, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (31285812, ROW('HZY', '3906'), 'FOCUS', 2009, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VANQUISH', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (16889101, ROW('XNE', '6786'), 'AMCSPIRIT', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (13615938, ROW('CKA', '6142'), 'Q7', 1984, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (61619852, ROW('RNN', '4736'), 'A4', 1990, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (69616579, ROW('DWA', '3195'), 'LEGEND', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (71422663, ROW('EPQ', '6962'), 'TL_MODELS', 1990, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (24471750, ROW('JTW', '5177'), 'X1', 1990, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (26693614, ROW('WGW', '2883'), 'LEGEND', 1990, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (12865550, ROW('ZOC', '4645'), 'ALLRDQUA', 1987, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (21307338, ROW('YAO', '5222'), 'NSX', 1986, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (15663929, ROW('ZOJ', '1212'), 'RSX', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (21798795, ROW('PNE', '0505'), 'CL_MODELS', 2003, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'TL_MODELS', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (46676659, ROW('WXE', '6314'), 'S4', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (69741163, ROW('XVN', '0651'), 'ALLRDQUA', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'AUDI100', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (78783762, ROW('NPX', '7511'), 'AZURE', 1991, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'V12VANT', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'FERCALIF', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (76409090, ROW('LRP', '6895'), 'SPID', 1990, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (61524414, ROW('EEJ', '4980'), 'ALFA8C', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (15663929, ROW('YYR', '0908'), 'EVORA', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (86440986, ROW('UNG', '4564'), 'LEGEND', 1985, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (49624598, ROW('STS', '6021'), 'LEGEND', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (45290555, ROW('MMF', '2367'), 'NSX', 2004, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'EVORA', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RSX', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (41090503, ROW('KXL', '7036'), 'FERCALIF', 1993, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'TL', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (65492779, ROW('CKY', '3271'), 'EVOQUE', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (99279003, ROW('IPE', '2281'), 'AMCSPIRIT', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (12446070, ROW('UOK', '3870'), 'S4', 1993, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (41090503, ROW('CZB', '7816'), 'C63AMG', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (83757595, ROW('FNL', '2412'), 'ALFA8C', 1991, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (78971443, ROW('JDZ', '1264'), 'TL_MODELS', 2011, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'ALFA164', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (71263787, ROW('MYS', '3750'), 'DB7', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (94044608, ROW('URH', '0897'), 'RL_MODELS', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (43736050, ROW('CGL', '8066'), 'VIGOR', 1972, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'V12VANT', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (60737316, ROW('JWJ', '2120'), '90', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (43268208, ROW('EBT', '6883'), 'AUDI200', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'A8', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (38435403, ROW('DER', '9197'), 'CL63AMG', 2006, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (93128927, ROW('AAP', '4195'), 'MDX', 2009, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (29868167, ROW('TVD', '4103'), 'ALFA164', 1999, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (37694232, ROW('BKM', '7636'), 'A3', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (12406273, ROW('GHA', '4407'), 'V12VANT', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (30696065, ROW('HUI', '6857'), 'AVENT', 2007, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '5000', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (46896095, ROW('MSP', '9625'), 'ALFA164', 1990, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (26422927, ROW('OPZ', '1791'), 'VANQUISH', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'MDX', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'A7', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VIGOR', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (65492779, ROW('EMX', '0733'), 'AMCALLIAN', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (92804602, ROW('LBL', '4338'), '80', 2003, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'S4', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (30365914, ROW('MUI', '8453'), 'RDX', 1997, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'MIL', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (13927211, ROW('WWK', '9526'), '90', 1987, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (35964582, ROW('GLF', '0102'), 'RL_MODELS', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'AMCALLIAN', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'A4', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LAGONDA', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RL_MODELS', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (60737316, ROW('LTQ', '5389'), 'Q7', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (93467690, ROW('FQH', '4838'), 'VIGOR', 1994, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (65049883, ROW('JSV', '1953'), 'SPID', 2005, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VIGOR', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (91476709, ROW('FLQ', '6687'), 'NSX', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VANQUISH', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (85372025, ROW('BKD', '7193'), 'LEGEND', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (84595840, ROW('TYV', '5149'), 'NSX', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (84693395, ROW('FBD', '1433'), 'VIGOR', 2007, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (27204504, ROW('UUX', '0098'), 'LEGEND', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VIGOR', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (69741163, ROW('XTO', '6194'), 'VANQUISH', 1996, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RL_MODELS', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (97602075, ROW('JCX', '4009'), 'E63AMG', 1989, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (79075137, ROW('VRM', '3420'), '4000', 1994, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (37593321, ROW('BGB', '3366'), 'A6', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (52278222, ROW('GPZ', '3632'), 'RDX', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (78443030, ROW('YLE', '2364'), 'VIGOR', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VANQUISH', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (97794267, ROW('QOL', '0716'), 'AUDI200', 2006, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'EVORA', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (43979748, ROW('FWA', '2106'), 'VANQUISH', 1987, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (29583253, ROW('VCO', '8267'), 'VIGOR', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (25732848, ROW('DYH', '0900'), 'TL_MODELS', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (89143769, ROW('COL', '6343'), 'VANQUISH', 1979, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'E63AMG', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (34393972, ROW('UHK', '1086'), 'FERCALIF', 2003, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (31000098, ROW('ZDW', '6297'), '370Z', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (81359559, ROW('BCG', '2155'), '80', 1989, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'AMCALLIAN', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VIGOR', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (83674543, ROW('UNO', '8742'), 'TL_MODELS', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (55067564, ROW('BQF', '8882'), 'VANQUISH', 1969, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (49980307, ROW('LOO', '1609'), 'VANQUISH', 1996, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VANQUISH', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (61934773, ROW('ZKA', '2639'), 'AVENT', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (31000098, ROW('YKM', '8305'), 'RL_MODELS', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (27609728, ROW('SAL', '7974'), 'DB7', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (46896095, ROW('LOJ', '1349'), 'LEGEND', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (20521780, ROW('NIO', '7932'), 'LEGEND', 1985, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (45647586, ROW('NOE', '8528'), 'RS6', 1965, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (40340630, ROW('NXJ', '9781'), 'VIRAGE', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'AUDI100', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (32569975, ROW('PJW', '7837'), 'AUDI200', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VIRAGE', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (45290555, ROW('JPR', '2796'), 'VANQUISH', 2007, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (37731274, ROW('NMZ', '1172'), 'A4', 1997, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (24122494, ROW('STM', '3352'), 'ALFA164', 2004, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (61171125, ROW('OJX', '4832'), 'VANQUISH', 1993, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (73920896, ROW('QBB', '0189'), 'NSX', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (84950553, ROW('YZJ', '2834'), 'LEGEND', 1999, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (22875745, ROW('JCX', '7919'), 'DB7', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (70505173, ROW('PMD', '3773'), 'LEGEND', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (56598631, ROW('XIM', '2533'), 'EAGLE', 2004, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (71971134, ROW('CPF', '2152'), 'TL_MODELS', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (59975939, ROW('UKU', '1660'), '3.2CL', 2013, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (86929394, ROW('QYJ', '0724'), 'FERCALIF', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (26692799, ROW('MRT', '1763'), 'RS4', 1996, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'FERCALIF', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (36707298, ROW('JRM', '8910'), 'VANQUISH', 2011, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '370Z', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (87803675, ROW('WQH', '8312'), 'EVORA', 1984, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'CL_MODELS', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'AUDI200', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (37593321, ROW('SOK', '4361'), 'LEGEND', 2005, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'SPID', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (86967919, ROW('ZNN', '9426'), 'LEGEND', 2005, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (95290933, ROW('PZS', '3015'), 'AMCSPIRIT', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (35409668, ROW('GCZ', '9909'), 'RL_MODELS', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (23395244, ROW('CUA', '7026'), 'RL_MODELS', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (98999590, ROW('FHT', '9320'), 'ALLRDQUA', 2007, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (24684854, ROW('AQK', '8052'), 'AUDI200', 2011, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (42141880, ROW('YYE', '6740'), 'ALLRDQUA', 2005, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'AMCENC', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (86967919, ROW('MBC', '9028'), 'AMCSPIRIT', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '370Z', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (27502051, ROW('FNJ', '1893'), 'A7', 2005, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (89492159, ROW('WUP', '9708'), 'VIGOR', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (86440986, ROW('WSB', '6211'), 'MDX', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (37576041, ROW('PGT', '1227'), 'RS4', 1979, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RSX', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (12178732, ROW('BAX', '3438'), '90', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (15026798, ROW('EXK', '7702'), 'S4', 1993, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (21468518, ROW('QAV', '4608'), '5000', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'MDX', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (89651062, ROW('THQ', '2083'), 'QUATTR', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'A7', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (66418020, ROW('ROU', '6190'), 'A3', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (44419217, ROW('PBX', '8078'), 'VANQUISH', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (30886727, ROW('MRQ', '3763'), 'RL_MODELS', 2009, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (25002793, ROW('NTT', '9702'), '3.2TL', 2007, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (73920896, ROW('RHZ', '7361'), 'Q7', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (12865550, ROW('VRG', '5194'), '370Z', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (86611731, ROW('EHN', '5272'), 'TL_MODELS', 1999, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'A3', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (74480550, ROW('EQS', '9144'), 'VANQUISH', 1984, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (27204504, ROW('JJX', '7724'), 'MDX', 2003, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'MDX', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (33904981, ROW('CKH', '7202'), 'ALFA164', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'ALFA164', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (47406317, ROW('HNJ', '2135'), 'ALLRDQUA', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (46083674, ROW('TOJ', '9703'), '3.2CL', 1999, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (19925780, ROW('CJH', '4256'), 'VANQUISH', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (56847366, ROW('GDQ', '0787'), 'VIRAGE', 1993, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '5000', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (59547356, ROW('MUO', '5164'), 'RL_MODELS', 1968, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (88005237, ROW('YBU', '9569'), 'ALFA164', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '3.2CL', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'A3', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'TL_MODELS', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VANQUISH', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (85386980, ROW('UER', '3525'), 'EAGLE', 2013, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (61934773, ROW('ZKK', '5880'),'MURANO', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (15505686, ROW('GDZ', '7451'), '3.2CL', 1994, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (73770672, ROW('LCD', '8163'), 'MDX', 1986, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (75217958, ROW('OMG', '3363'), 'LEGEND', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (29126064, ROW('TFP', '0091'), 'CON', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (48188019, ROW('TRX', '2756'), 'RDX', 1997, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (72071195, ROW('MOH', '7164'), 'Q7', 2006, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (55764886, ROW('BIL', '1138'), 'X1', 2001, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (25014474, ROW('IRX', '7915'), 'VANQUISH', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (84950553, ROW('YHE', '1090'), 'LEGEND', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'QUATTR', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (40782805, ROW('TPL', '4587'), 'RS6', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (18977175, ROW('DOQ', '0049'), 'VANQUISH', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (66405654, ROW('RVX', '6510'), 'RL_MODELS', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (37593321, ROW('YMZ', '5507'), 'EVORA', 1998, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (25366977, ROW('BAQ', '0767'), 'VANQUISH', 2008, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (96443428, ROW('WLG', '4992'), 'RL_MODELS', 1985, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'EVORA', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (83757595, ROW('BJQ', '2549'), 'VANQUISH', 1985, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'AZURE', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (84950553, ROW('TVF', '2262'), 'RL_MODELS', 1996, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (78783762, ROW('PKU', '6017'), 'VANQUISH', 1999, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (56319863, ROW('DCY', '6257'), 'QUATTR', 2006, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (87246564, ROW('PRI', '2129'), 'RL_MODELS', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (67570834, ROW('FZF', '8664'), 'VANQUISH', 1996, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RS6', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (66084267, ROW('YZV', '5846'), 'RS4', 2009, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VANQUISH', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (11856678, ROW('DAW', '6975'), 'CL_MODELS', 2009, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (99154390, ROW('WIN', '0373'), 'AUDI100', 2002, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'A3', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (43226962, ROW('LVV', '4790'), 'AUDI200', 1993, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (55922039, ROW('DJF', '3133'), 'AMCENC', 1999, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'DB7', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (77536345, ROW('IRG', '0038'), 'VANQUISH', 1994, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (93507680, ROW('KSX', '1373'), 'VIGOR', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'AUDI100', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'DB7', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'MIL', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'RS6', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (46676659, ROW('XWJ', '1642'), 'VIGOR', 1996, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (86967919, ROW('EXT', '2741'), 'VANQUISH', 2003, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (11883566, ROW('JPR', '3592'), '90', 2007, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (55764886, ROW('ERQ', '1452'), 'AMCALLIAN', 1985, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (20627308, ROW('FGE', '2178'), 'LEGEND', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VANQUISH', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'TL', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (53079457, ROW('GTK', '5071'), '3.2TL', 2007, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'LEGEND', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (73451525, ROW('YFY', '8152'), 'VIRAGE', 1994, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (68167178, ROW('SEC', '6736'), 'PULSAR', 2003, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'CON', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'VITARA', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (56984688, ROW('BZJ', '4230'), 'XL7', 1995, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (40794387, ROW('LGM', '3536'), 'QUATTR', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (53473683, ROW('XHB', '4858'), 'TL_MODELS', 2006, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (60337612, ROW('ISK', '1259'), '4RUN', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (21468518, ROW('DLI', '1387'), 'DEFEND', 1997, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'AUDI200', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (37731274, ROW('QCM', '3740'),'MURANO', 1994, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'AUDI100', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, '2.2CL', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'TL_MODELS', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (10368099, ROW('EBR', '1553'), '2.2CL', 2007, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'DB7', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (64672437, ROW('AJT', '6691'), '80', 1986, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (48875936, ROW('UAS', '6296'), 'LEGEND', 2000, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (11525951, ROW('ALW', '2649'), 'RS6', 2010, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (null, null, 'QUATTR', 2018, 'new');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (59548136, ROW('HSK', '3484'), '4000', 2012, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (49624598, ROW('VDV', '7433'), 'RS4', 2007, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (21798795, ROW('LLK', '9125'), 'VANQUISH', 1985, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (41238491, ROW('UBT', '3125'), 'INTEG', 1992, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (23395244, ROW('CSF', '3718'), 'VIGOR', 1989, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (33111878, ROW('SJT', '2791'), 'RL_MODELS', 2005, 'used');
insert into car_warehouse (owner_id, plate, model_id, manufacturing_date, condition) values (25366977, ROW('CJH', '0317'), 'ALLRDQUA', 1998, 'used');
